### ISSUE TITLE
Support constants

### ISSUE THREAD

**Issue by itsdfish** [JuliaAPlavin/RectiGrids.jl#5]
Thank you for putting this package together. It is very useful for performing grid searches. One limitation is that constants cannot be added (unless explicitly wrapped in `[]`). For example: 

```julia
Θ =  RectiGrids.grid(γ = .1:.1:.5, β = .3:.1:.9, z = 1)
ERROR: MethodError: no method matching keyarr(::Int64)
The function `keyarr` exists, but no method is defined for this combination of argument types
```

One solution I found was to extend `keyarr` and `valuearr` as follows:

```julia
keyarr(x) = nothing
valarr(x) = [x]
```

The result is the following:

```julia
julia> Θ =  RectiGrids.grid(γ = .1:.1:.5, β = .3:.1:.9, z = 1)
3-dimensional KeyedArray(NamedDimsArray(...)) with keys:
↓   γ ∈ 5-element StepRangeLen{Float64,...}
→   β ∈ 7-element StepRangeLen{Float64,...}
◪   z ∈ 1-element Vector{Int64}
And data, 5×7×1 RectiGrids.RectiGridArr{(:γ, :β, :z), @NamedTuple{γ::Float64, β::Float64, z::Int64}, 3, Tuple{Nothing, Nothing, Nothing}, Tuple{StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, Vector{Int64}}}:
[:, :, 1] ~ (:, :, 1):
      (0.3)  (0.4)  (0.5)  (0.6)  (0.7)  (0.8)  (0.9)
   ⋮                                ⋮           

julia> Θ[1]
(γ = 0.1, β = 0.3, z = 1)

julia> Θ[2]
(γ = 0.2, β = 0.3, z = 1)
```

Would it be possible to support something like this?

**Comment by aplavin** [comment]
Hmm, interesting suggestion!
Currently, all the parameters need to be passed as arrays, indeed. This make it possible to directly map them to axiskeys of the resulting grid: eg, `axiskeys(Θ, :β) === .3:.1:.9`, the exact same object one passed to the `grid` constructor.

It's feasible and intuitive to allow passing other iterables to `grid`, so that the constructor calls `collect()` on them automatically. Then, numbers would work the way you suggest – they are iterable in Julia.
Other iterators (eg, generators like `(i^2 for i in 1:10)`) would also work. A potentially confusing case would be types like strings – they would be turned into arrays of characters. But it should be fine, that's how stuff works elsewhere in Julia as well.

I'll probably implement `collect`ing all non-array arguments, agree that it can be useful!

**Comment by aplavin** [comment]
Should work in the new version, v0.1.19!
